# Generated by Django 3.2.18 on 2023-05-30 23:33

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('baja', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('dni', models.IntegerField(verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matricula')),
                ('baja', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('legajo', models.CharField(max_length=10, verbose_name='Legajo')),
            ],
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.usuario')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('domicilio', models.CharField(max_length=20, verbose_name='Domicilio')),
                ('foto', models.ImageField(null=True, upload_to='perfiles/', verbose_name='Foto Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(default=None, null=True, verbose_name='Fecha de inicio')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Portada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('horario', models.CharField(default=None, max_length=100, null=True, verbose_name='Horario')),
                ('link_meet', models.URLField(max_length=100, verbose_name='Link de Meet')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_slug', models.SlugField(max_length=100, verbose_name='Nombre Slug')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('url', models.URLField(max_length=100, verbose_name='Url')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/proyecto/', verbose_name='Portada')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('estado', models.IntegerField(choices=[(1, 'Inscripto'), (2, 'Cursando'), (3, 'Egresado')], default=1)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.comision')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='comision',
            name='estudiantes',
            field=models.ManyToManyField(through='administracion.Inscripcion', to='administracion.Estudiante'),
        ),
    ]
