# Generated by Django 3.2.18 on 2023-05-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, null=True)),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('matricula', models.CharField(max_length=10, null=True, verbose_name='Matricula')),
                ('baja', models.BooleanField(default=0, null=True)),
                ('legajo', models.CharField(max_length=10, null=True, verbose_name='Legajo')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('horario', models.CharField(default=None, max_length=100, null=True, verbose_name='Horario')),
                ('link_meet', models.URLField(max_length=100, verbose_name='Link de Meet')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.curso')),
            ],
        ),
    ]
