# Generated by Django 3.2.18 on 2023-05-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_estudiante_instructor_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstudianteAbs',
        ),
        migrations.DeleteModel(
            name='InstructorAbs',
        ),
        migrations.DeleteModel(
            name='PersonaU',
        ),
    ]
