# Generated by Django 3.2.18 on 2023-05-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20230511_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionMTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('horario', models.CharField(default=None, max_length=100, null=True, verbose_name='Horario')),
                ('link_meet', models.URLField(max_length=100, verbose_name='Link de Meet')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.curso')),
                ('estudiantes', models.ManyToManyField(to='administracion.Estudiante')),
            ],
        ),
    ]
